//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEZINCE.WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceImage
    {
        public int Id { get; set; }
        public string ImageName { get; set; }
        public string Guid { get; set; }
        public string Path { get; set; }
        public int PlaceId { get; set; }
    
        public virtual Place Place { get; set; }
    }
}
